rm(list=ls())
setwd("C:/Users/drambaccussing/OneDrive - University of Dundee/RESEARCH/Scotland Present Value Housing/Data")
getwd()
library(readxl)
rdata <- read_excel("rdata.xlsx")
frame = as.data.frame(rdata)
data1 = as.data.frame(unclass(frame))
data1$Location =as.factor(data1$Location)
ggplot(data1, aes(x = Price, fill = Location))+geom_density(col=NA, alpha = 0.35)
ggplot(data1, aes(x = Price.Rent.Ratio, fill = Location))+geom_density(col=NA, alpha = 0.35)
ggplot(data1, aes(x = Rent, fill = Location))+geom_density(col=NA, alpha = 0.35)
